/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TableCrispr {
    'complete_data': string;
  }
}

declare global {


  interface HTMLTableCrisprElement extends Components.TableCrispr, HTMLStencilElement {}
  var HTMLTableCrisprElement: {
    prototype: HTMLTableCrisprElement;
    new (): HTMLTableCrisprElement;
  };
  interface HTMLElementTagNameMap {
    'table-crispr': HTMLTableCrisprElement;
  }
}

declare namespace LocalJSX {
  interface TableCrispr extends JSXBase.HTMLAttributes<HTMLTableCrisprElement> {
    'complete_data'?: string;
  }

  interface IntrinsicElements {
    'table-crispr': TableCrispr;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


