/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LinearCard {
    'all_sgrna': string;
    'gene': string;
    'nb_step': string;
    'width_bar': string;
  }
}

declare global {


  interface HTMLLinearCardElement extends Components.LinearCard, HTMLStencilElement {}
  var HTMLLinearCardElement: {
    prototype: HTMLLinearCardElement;
    new (): HTMLLinearCardElement;
  };
  interface HTMLElementTagNameMap {
    'linear-card': HTMLLinearCardElement;
  }
}

declare namespace LocalJSX {
  interface LinearCard extends JSXBase.HTMLAttributes<HTMLLinearCardElement> {
    'all_sgrna'?: string;
    'gene'?: string;
    'nb_step'?: string;
    'width_bar'?: string;
  }

  interface IntrinsicElements {
    'linear-card': LinearCard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


